# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('DL', 'diler'), ('MT', 'market'), ('PS', 'person'), ('PD', 'provider')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.IntegerField(default=0)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PartnerSet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(choices=[('AC', 'accept'), ('RT', 'return'), ('RC', 'receipt')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='transactionset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransactionStatus'),
        ),
        migrations.AddField(
            model_name='transactionset',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StorageSet'),
        ),
        migrations.AddField(
            model_name='productset',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StorageSet'),
        ),
        migrations.AddField(
            model_name='productset',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransactionSet'),
        ),
    ]
