# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('DL', 'diler'), ('MT', 'market'), ('PS', 'person')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductSet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProductSet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'accept'), ('RT', 'return')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TransactionStatus'),
        ),
    ]
