# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
