# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181003_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='form',
            field=models.CharField(choices=[('DL', 'diler'), ('MT', 'market'), ('PS', 'person'), ('PD', 'provider')], max_length=2),
        ),
        migrations.AlterField(
            model_name='transactionstatus',
            name='status',
            field=models.CharField(choices=[('AC', 'accept'), ('RT', 'return'), ('RC', 'receipt')], max_length=2),
        ),
    ]
